---
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  database: <%= ENV.fetch("DB_DATABASE") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host:     <%= ENV.fetch("DB_HOST") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
